title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics: UA-XXXXXXXX-X  # Replace this with your Google Analytics tracking ID if you have one
theme: jekyll-theme-minimal
